version: '3.8'

services:
  mongo:
    image: mongo:latest
    container_name: mongodb_skydrop
    restart: always
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: skydrop
      MONGO_INITDB_ROOT_PASSWORD: ulysseetchatgptnefontq1
    volumes:
      - mongo-data:/data/db
volumes:
  mongo-data:
